# === docker-compose.dev.yml (SITL Development Setup) ===
#
# This file configures the development environment for PX4 SITL simulation.
# It uses UDP communication for the Micro XRCE-DDS Agent to connect to PX4 SITL.
#
# By default, it's configured for a single drone (drone1) with:
# - ROS 2 node name: drone1
# - Drone name: drone1
# - PX4 namespace: /fmu/
# - MAVLink System ID: 1
#
# MULTI-DRONE SETUP:
# To run multiple drones in SITL:
# 1. Copy this file for each additional drone (e.g., docker-compose.dev.drone2.yml)
# 2. Update the command section for each drone with its specific configuration:
#    - __node: Unique ROS 2 node name (e.g., drone2)
#    - drone_name: Logical drone name (e.g., drone2)
#    - px4_namespace: PX4 topic namespace (e.g., /px4_1/fmu/ for ID 2)
#    - mav_sys_id: Unique MAVLink System ID (e.g., 2)
#
# Run with: docker compose -f docker-compose.dev.yml up -d
#

services:
  # --- Drone Core Service ---
  # Runs the main drone control logic (drone_core node)
  drone_core2: # Changed from drone_core to drone_core2
    build:
      context: . # Build using the Dockerfile in the current directory (ws_droneOS)
      dockerfile: drone_core.Dockerfile
    container_name: drone_core_node2 # Explicit name for the running container
    network_mode: "host" # ESSENTIAL: Use the host's network for Tailscale & agent comms
    restart: unless-stopped # Optional: Restart policy
    volumes:
      # Mount a host directory into the container for persistent logs
      - ./logs:/root/ws_droneOS/logs
    environment:
      # Set the ROS 2 DDS implementation (ensure it matches your setup)
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      # Increase ROS log verbosity
      - ROS_LOG_SEVERITY_THRESHOLD=debug
      # Whitelist specific interface for Fast-RTPS
      - FASTRTPS_WHITELIST_INTERFACES=tailscale0
    # --- COMMAND OVERRIDE (CRITICAL) ---
    # Provides the specific arguments for THIS drone.
    # The ENTRYPOINT script will source setup files first
    command: [
      "ros2", "run", "drone_core", "drone_core",
      "--ros-args",
      # --- Configuration for Drone 2 ---
      "-r", "__node:=drone2",             # Unique ROS 2 node name
      "-p", "drone_name:=drone2",         # Logical drone name parameter
      "-p", "px4_namespace:=/px4_1/fmu/", # PX4 topic namespace (e.g., /px4_1/fmu/ for ID 2)
      "-p", "mav_sys_id:=2"               # Unique MAVLink System ID
    ]

volumes:
  logs: # Declares that the host path './logs' is expected
    driver: local
