# === docker-compose.yml (Template for a SINGLE Drone Raspberry Pi) ===
#
# CONTEXT: This file is configured for a single real drone, intended to run on its
# dedicated hardware (e.g., Raspberry Pi). By default, it uses the following configuration:
# - ROS 2 node name: drone1
# - Drone name: drone1
# - PX4 namespace: /fmu/
# - MAVLink System ID: 1
#
# MULTI-DRONE SETUP:
# To run multiple real drones, you need to:
# 1. Copy this file for each additional drone (e.g., docker-compose.drone2.yml)
# 2. Update the command section for each drone with its specific configuration:
#    - __node: Unique ROS 2 node name (e.g., drone2)
#    - drone_name: Logical drone name (e.g., drone2)
#    - px4_namespace: PX4 topic namespace (e.g., /px4_1/fmu/ for ID 2)
#    - mav_sys_id: Unique MAVLink System ID (e.g., 2)
#
# Future improvements could make this more dynamic through environment variables
# or configuration files.
#
# Place this file in the root of the ws_droneOS workspace on the target RPi.
# The default configuration should work for a single drone setup.
# For multiple drones, customize the configuration as described above.
# Run with: docker compose up -d
#

services:
  # --- Drone Core Service ---
  # Runs the main drone control logic (drone_core node)
  drone_core: # Service name (can be customized, e.g., drone1_core)
    build:
      context: . # Build using the Dockerfile in the current directory (ws_droneOS)
      dockerfile: drone_core.Dockerfile
    container_name: drone_core_node # Explicit name for the running container
    network_mode: "host" # ESSENTIAL: Use the host's network for Tailscale & agent comms
    restart: unless-stopped # Optional: Restart policy
    volumes:
      # Mount a host directory into the container for persistent logs
      - ./logs:/root/ws_droneOS/logs
    environment:
      # Set the ROS 2 DDS implementation (ensure it matches your setup)
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      # Increase ROS log verbosity
      - ROS_LOG_SEVERITY_THRESHOLD=debug
      # Whitelist specific interface for Fast-RTPS
      - FASTRTPS_WHITELIST_INTERFACES=tailscale0
    depends_on:
      # Ensure the agent starts before the core logic
      - micro_agent
    # --- COMMAND OVERRIDE (CRITICAL) ---
    # Provides the specific arguments for THIS drone.
    # The ENTRYPOINT script will source setup files first
    command: [
      "ros2", "run", "drone_core", "drone_core",
      "--ros-args",
                 # --- !!! CUSTOMIZE THESE ARGUMENTS FOR THIS SPECIFIC DRONE !!! ---
      # --- Configuration for Drone 1 (Active) ---
      "-r", "__node:=drone1",             # Unique ROS 2 node name
      "-p", "drone_name:=drone1",         # Logical drone name parameter
      "-p", "px4_namespace:=/fmu/", # PX4 topic namespace (e.g., /px4_0/fmu/ for ID 1)
      "-p", "mav_sys_id:=1"               # Unique MAVLink System ID

      # --- Example Configuration for Drone 2 (Commented Out) ---
      # "-r", "__node:=drone2",             # Unique ROS 2 node name
      # "-p", "drone_name:=drone2",         # Logical drone name parameter
      # "-p", "px4_namespace:=/px4_1/fmu/", # PX4 topic namespace (e.g., /px4_1/fmu/ for ID 2)
      # "-p", "mav_sys_id:=2"               # Unique MAVLink System ID

      # --- Example Configuration for Drone 3 (Commented Out - Original) ---
      # "-r", "__node:=drone3",             # Unique ROS 2 node name
      # "-p", "drone_name:=drone3",         # Logical drone name parameter
      # "-p", "px4_namespace:=/px4_2/fmu/", # PX4 topic namespace (e.g., /px4_2/fmu/ for ID 3)
      # "-p", "mav_sys_id:=3"               # Unique MAVLink System ID
    ]

  # --- Micro XRCE-DDS Agent Service ---
  # Bridges communication between ROS 2 (DDS) and PX4 (Serial)
  micro_agent:
    build:
      context: . # Build using the micro_agent.Dockerfile in the current directory
      dockerfile: micro_agent.Dockerfile
    container_name: micro_agent_service # Explicit name for the running container
    network_mode: "host" # ESSENTIAL: Use the host's network for core comms & PX4 device access
    restart: unless-stopped # Optional: Restart policy
    devices:
      # Map the stable host symlink (created by udev rule in /etc/udev/rules.d/99-pixhawk.rules)
      # to the path the agent expects inside the container (/dev/ttyUSB0).
      # The agent command MUST use the container path (/dev/ttyUSB0).
      - "/dev/pixhawk-telem2:/dev/ttyUSB0" # STABLE_HOST_SYMLINK:CONTAINER_PATH
    environment:
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      # Increase ROS log verbosity
      - ROS_LOG_SEVERITY_THRESHOLD=debug
      # Whitelist specific interface for Fast-RTPS
      - FASTRTPS_WHITELIST_INTERFACES=tailscale0
    # --- Command for serial communication ---
    command: > # Use multi-line format for clarity
      bash -c "sleep 2 && \
               MicroXRCEAgent serial --dev /dev/ttyUSB0 -b 921600"
    # Note: Ensure the user running Docker on the host (e.g., 'rodrigo') has permission for /dev/ttyUSB0 (belongs to 'dialout' group).
    # If not, run: sudo usermod -a -G dialout rodrigo (or relevant user) and then REBOOT or log out/in.

volumes:
  logs: # Declares that the host path './logs' is expected
    driver: local
