OffboardControl
State
Initial state.
rclcpp::Node* OffboardControl::node_
Pointer to ROS2 node.
Referenced by command_response_callback, OffboardControl, publish_trajectory_setpoint, send_vehicle_command, start, stop, timer_callback.
std::string OffboardControl::ns_
PX4 namespace.
Referenced by OffboardControl.
rclcpp::TimerBase::SharedPtr OffboardControl::timer_
Timer for periodic publishing.
Referenced by start, stop.
rclcpp::Publisher<px4_msgs::msg::OffboardControlMode>::SharedPtr OffboardControl::offboard_control_mode_pub_
Publisher for offboard control mode.
Referenced by OffboardControl, timer_callback.
rclcpp::Publisher<px4_msgs::msg::TrajectorySetpoint>::SharedPtr OffboardControl::trajectory_setpoint_pub_
Publisher for trajectory setpoints.
Referenced by OffboardControl, publish_trajectory_setpoint.
rclcpp::Client<px4_msgs::srv::VehicleCommand>::SharedPtr OffboardControl::vehicle_command_client_
Client for vehicle commands.
Referenced by OffboardControl, send_vehicle_command.
State OffboardControl::state_
Current state.
Referenced by get_state, start, timer_callback.
uint8_t OffboardControl::service_result_
Result of last service call.
Referenced by command_response_callback, timer_callback.
bool OffboardControl::service_done_
Service call completion flag.
Referenced by command_response_callback, send_vehicle_command, timer_callback.
int OffboardControl::offboard_setpoint_counter_
Counter for offboard setpoints.
Referenced by timer_callback.
OffboardControl::OffboardControl(rclcpp::Node *node, const std::string &px4_namespace)
Construct a new OffboardControl object.
Constructs an OffboardControl instance. node Pointer to the ROS2 node px4_namespace PX4 namespace for communication Initializes publishers and clients for PX4 communication. Sets up the offboard control mode publisher, trajectory setpoint publisher, and vehicle command client. node Pointer to the ROS 2 node px4_namespace Namespace for PX4 communication topics
References node_, ns_, offboard_control_mode_pub_, trajectory_setpoint_pub_, vehicle_command_client_.
void OffboardControl::start()
Start publishing offboard control mode messages and state machine.
Starts the offboard control mode. Initializes the timer for publishing offboard control mode messages at 2 Hz (required by PX4) and begins the state machine for transitioning to offboard mode.
References init, node_, state_, timer_, timer_callback.
void OffboardControl::stop()
Stop publishing offboard control mode messages.
Stops the offboard control mode. Cancels the timer and stops publishing offboard control mode messages.
References node_, timer_.
void OffboardControl::publish_trajectory_setpoint(float x, float y, float z, float yaw)
Publish a trajectory setpoint.
Publishes a trajectory setpoint to PX4. x Target x position in meters y Target y position in meters z Target z position in meters yaw Target yaw angle in radians Sends a position and yaw setpoint to the PX4 flight controller. x X position in meters (NED frame) y Y position in meters (NED frame) z Z position in meters (NED frame, positive down) yaw Yaw angle in radians
References node_, trajectory_setpoint_pub_.
State OffboardControl::get_state() const
Get the current state of the offboard control.
Current state
References state_.
void OffboardControl::timer_callback()
Timer callback for publishing offboard control mode and state machine.
Timer callback for publishing offboard control mode messages. This callback is executed at 2 Hz and handles: Publishing the offboard control mode message Managing the state machine for transitioning to offboard mode Handling arming sequence
References arm_requested, armed, init, node_, offboard_control_mode_pub_, offboard_requested, offboard_setpoint_counter_, send_vehicle_command, service_done_, service_result_, state_, wait_for_stable_offboard_mode.
Referenced by start.
void OffboardControl::send_vehicle_command(uint16_t command, float param1=0.0f, float param2=0.0f)
Send a vehicle command to PX4.
Sends a vehicle command to PX4. command Command code param1 First parameter param2 Second parameter Constructs and sends a vehicle command message to PX4 through the vehicle command service. command The command ID to send param1 First parameter for the command param2 Second parameter for the command
References command_response_callback, node_, service_done_, vehicle_command_client_.
Referenced by timer_callback.
void OffboardControl::command_response_callback(rclcpp::Client< px4_msgs::srv::VehicleCommand >::SharedFuture future)
Callback for vehicle command response.
Callback for vehicle command service responses. Handles the response from the vehicle command service, logging the result and updating the service status. future Future object containing the service response
References node_, service_done_, service_result_.
Referenced by send_vehicle_command.