version: '3.8'

services:
  discovery_server:
    image: ros:humble
    container_name: fastdds_discovery_server
    network_mode: host
    environment:
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - FASTDDS_DEFAULT_PROFILES_FILE=/root/fastdds_config_ground.xml
    volumes:
      - ../../fastdds_config_ground.xml:/root/fastdds_config_ground.xml:ro
    command: >
      bash -lc "
        apt-get update &&
        apt-get install -y fastdds-tools &&
        echo 'Starting Fast DDS Discovery Server on 100.101.149.9:11811...' &&
        fastdds discovery -i 1 -l 100.101.149.9 -p 11811
      "
    restart: unless-stopped

  rosbridge:
    image: ros:humble
    container_name: rosbridge_server
    network_mode: host
    environment:
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - FASTDDS_DEFAULT_PROFILES_FILE=/root/fastdds_config_ground.xml
    volumes:
      - ../../fastdds_config_ground.xml:/root/fastdds_config_ground.xml:ro
      - ../../install:/root/ws_droneOS/install:rw
      - ../../src:/root/ws_droneOS/src:ro
    command: >
      bash -lc "
        apt-get update &&
        apt-get install -y ros-humble-rosbridge-suite &&
        source /opt/ros/humble/setup.bash &&
        source /root/ws_droneOS/install/setup.bash ||
        true &&
        echo 'Starting rosbridge on :9090...' &&
        ros2 launch rosbridge_server rosbridge_websocket_launch.xml port:=9090
      "
    restart: unless-stopped

  telemetry_publisher:
    image: ros:humble
    container_name: telemetry_publisher
    network_mode: host
    environment:
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - FASTDDS_DEFAULT_PROFILES_FILE=/root/fastdds_config_ground.xml
    volumes:
      - ../../fastdds_config_ground.xml:/root/fastdds_config_ground.xml:ro
      - ../../install:/root/ws_droneOS/install:rw
      - ../../src:/root/ws_droneOS/src:ro
    command: >
      bash -lc "
        source /opt/ros/humble/setup.bash &&
        source /root/ws_droneOS/install/setup.bash &&
        echo 'Starting telemetry publisher...' &&
        ros2 run drone_core telemetry_publisher
          --ros-args
          -p drone_namespaces:=['px4_1']
          -p publish_rate_hz:=10
          -p enable_rosbridge_topics:=true
          -p enable_get_state_services:=true
      "
    restart: unless-stopped
